/**
 * x402 Service — Report Generator
 *
 * POST /api/x402/report-generator
 * Body: { cards: KnowledgeCard[], title?: string }
 * Response: { markdown, sections, word_count }
 *
 * 业务：将多张 KnowledgeCard 合并为一份研究报告 markdown。
 * 复用 lib/parser.ts:exportToMarkdown，无 LLM 调用（默认模式），单次成本≈0。
 */

import { NextResponse } from 'next/server'
import { withX402 } from '@/lib/x402/gate'
import { BusinessError } from '@/lib/x402/run-paid'
import { exportToMarkdown } from '@/lib/parser'

export const dynamic = 'force-dynamic'
export const runtime = 'nodejs'
export const maxDuration = 60

const MAX_CARDS = 20

const { GET, POST, OPTIONS } = withX402(
  { priceUsd: 0.03, description: 'Report generator service (multi-card markdown)' },
  async (body) => {
    const cards = body?.cards
    if (!Array.isArray(cards) || cards.length === 0) {
      throw new BusinessError(400, 'invalid_input', 'cards (non-empty array) is required')
    }
    if (cards.length > MAX_CARDS) {
      throw new BusinessError(400, 'invalid_input', `cards length must be ≤ ${MAX_CARDS}`)
    }

    // 校验每张卡都有 title
    for (let i = 0; i < cards.length; i++) {
      if (!cards[i] || typeof cards[i] !== 'object' || !cards[i].title) {
        throw new BusinessError(400, 'invalid_input', `cards[${i}] is missing title`)
      }
    }

    const title = typeof body.title === 'string' && body.title.trim()
      ? body.title.trim()
      : 'ResearchKit Report'

    // 逐张导出 markdown，用分隔线串接
    const sections: Array<{ title: string; markdown: string; word_count: number }> = []
    let combined = `# ${title}\n\n`
    combined += `> Generated by ResearchKit OS — ${cards.length} knowledge card(s)\n\n`

    for (let i = 0; i < cards.length; i++) {
      const card = cards[i]
      let md: string
      try {
        md = exportToMarkdown(card, card.source)
      } catch (e) {
        throw new BusinessError(502, 'export_failed', `exportToMarkdown failed for cards[${i}]: ${e instanceof Error ? e.message : String(e)}`)
      }
      combined += `---\n\n${md}\n\n`
      sections.push({
        title: card.title,
        markdown: md,
        word_count: md.split(/\s+/).filter(Boolean).length,
      })
    }

    const totalWordCount = combined.split(/\s+/).filter(Boolean).length

    return NextResponse.json({
      markdown: combined,
      sections,
      word_count: totalWordCount,
      card_count: cards.length,
    })
  }
)

export { GET, POST, OPTIONS }
