'use client'

import { useState, useRef, useEffect } from 'react'
import KnowledgeGraph, { buildKnowledgeGraph } from '@/components/KnowledgeGraph'

type InputMode = 'text' | 'url' | 'pdf' | 'batch'

/**
 * 按语言切换 UI 标签 — 升级版
 * 中文论文用中文标签，英文论文用英文标签，避免错配
 *
 * 升级版（locale 感知）：
 * - zh-CN → 中文标签
 * - 其他 locale → 英文标签（统一 fallback）
 * - 兼容旧的 language 字段（'zh' 仍走中文路径）
 */
function getLabels(language?: string, locale?: string) {
  const isZh = language === 'zh' || locale === 'zh-CN'
  return {
    knowledgeCard: isZh ? '📖 知识卡' : '📖 Knowledge Card',
    authors: isZh ? '作者' : 'Authors',
    field: isZh ? '领域' : 'Field',
    year: isZh ? '年份' : 'Year',
    difficulty: isZh ? '难度' : 'Difficulty',
    readingTime: isZh ? '阅读时长' : 'Reading time',
    min: isZh ? '分钟' : 'min',
    takeaway: isZh ? '🎯 核心结论' : '🎯 Takeaway',
    whyItMatters: isZh ? '💭 为什么重要' : '💭 Why It Matters',
    whatSurprised: isZh ? '✨ 最令人意外' : '✨ What Surprised Me',
    whoShouldRead: isZh ? '👥 谁应该读' : '👥 Who Should Read',
    summary: isZh ? '📌 一句话摘要' : '📌 Summary',
    researchGoals: isZh ? '🎯 研究目的' : '🎯 Research Goals',
    innovation: isZh ? '💡 创新点 / 主要贡献' : '💡 Innovation / Key Contributions',
    methodology: isZh ? '🔧 方法论' : '🔧 Methodology',
    experiments: isZh ? '🧪 实验设置' : '🧪 Experiments',
    results: isZh ? '📊 主要结果' : '📊 Results',
    limitations: isZh ? '⚠️ 局限性' : '⚠️ Limitations',
    futureWork: isZh ? '🔮 未来工作' : '🔮 Future Work',
    applications: isZh ? '🚀 应用场景' : '🚀 Applications',
    datasets: isZh ? '📁 数据集' : '📁 Datasets',
    keyTerms: isZh ? '🔤 关键术语' : '🔤 Key Terms',
    recommendations: isZh ? '📚 推荐阅读' : '📚 Recommended Reading',
    references: isZh ? '📚 参考文献 / 推荐阅读' : '📚 References',
    structure: isZh ? '📐 文章结构' : '📐 Structure',
    andOthers: isZh ? '等' : 'et al.',
    quality: isZh ? '质量评分' : 'Quality',
    completeness: isZh ? '完整度' : 'Completeness',
    confidence: isZh ? '置信度' : 'Confidence',
    evidence: isZh ? '证据强度' : 'Evidence',
    tags: isZh ? '标签' : 'Tags',
    generatedBy: isZh ? '由 ResearchKit OS 生成 — AI 研究操作系统' : 'Generated by ResearchKit OS — AI Research Operating System',
  }
}

export default function Home() {
  const [mode, setMode] = useState<InputMode>('text')
  const [input, setInput] = useState('')
  const [result, setResult] = useState<any>(null)
  const [batchResults, setBatchResults] = useState<any[]>([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [copied, setCopied] = useState<'md' | 'obsidian' | 'mindmap' | null>(null)
  const [markdown, setMarkdown] = useState('')
  const [obsidian, setObsidian] = useState('')
  const [pdfFile, setPdfFile] = useState<File | null>(null)
  const [dragging, setDragging] = useState(false)
  const [showObsidian, setShowObsidian] = useState(false) // 已废弃（用 exportTab 代替），保留避免破坏其他引用
  const [exportTab, setExportTab] = useState<'markdown' | 'obsidian' | 'mindmap'>('markdown')
  const [plan, setPlan] = useState<any>(null)
  const [execution, setExecution] = useState<any[]>([])
  const [reflection, setReflection] = useState<any>(null)
  const [agentMeta, setAgentMeta] = useState<any>(null)
  const [toolCalls, setToolCalls] = useState<any[]>([])
  const [iterations, setIterations] = useState<any[]>([])
  const [totalIterations, setTotalIterations] = useState(0)
  const [uiMode, setUiMode] = useState<'simple' | 'advanced'>('simple')
  const [markdownPreviewOpen, setMarkdownPreviewOpen] = useState(false)
  const [pipelineExpanded, setPipelineExpanded] = useState(false)
  const [mindmap, setMindmap] = useState('')
  const [mindmapSvg, setMindmapSvg] = useState<string | null>(null)
  const [mindmapError, setMindmapError] = useState<string | null>(null)
  const [showMermaidSource, setShowMermaidSource] = useState(false) // 折叠 Mermaid 源码
  const [progressStage, setProgressStage] = useState(0) // 0=未开始, 1-6=各阶段, 7=完成
  const [progressStartedAt, setProgressStartedAt] = useState<number>(0)
  const [, setTick] = useState(0) // 用于强制 re-render 更新进度面板"已耗时"
  const fileInputRef = useRef<HTMLInputElement>(null)
  const mindmapRef = useRef<HTMLDivElement>(null)

  // 进度面板"已耗时"实时刷新：每秒强制 re-render
  useEffect(() => {
    if (progressStage === 0 || progressStage === 7) return
    const interval = window.setInterval(() => setTick(t => t + 1), 1000)
    return () => window.clearInterval(interval)
  }, [progressStage])

  // 进度阶段定义 — 与 coordinator.ts 实际执行流程一致
  const STAGES = [
    { id: 1, label: 'Document Loaded', icon: '📄', desc: '读取文档/URL/PDF 内容' },
    { id: 2, label: 'Plan Generated', icon: '🧠', desc: 'Planner LLM 自主规划执行步骤' },
    { id: 3, label: 'Concepts Extracted', icon: '🔬', desc: 'Reader + Analyzer + Terminology 并行分析' },
    { id: 4, label: 'Knowledge Card Built', icon: '🏗️', desc: 'KnowledgeBuilder 汇总成知识卡' },
    { id: 5, label: 'Reflection Loop', icon: '🔁', desc: '反思结果，必要时补调 Agent' },
    { id: 6, label: 'Exports Ready', icon: '📤', desc: '生成 Markdown / Obsidian / Knowledge Graph' },
  ]

  const handleSubmit = async () => {
    if (mode === 'pdf') {
      if (!pdfFile) {
        setError('请上传 PDF 文件')
        return
      }
    } else if (mode === 'batch') {
      if (!input.trim()) {
        setError('请输入多个 URL（每行一个）')
        return
      }
    } else if (!input.trim()) {
      setError(mode === 'url' ? '请输入 URL' : '请输入论文/文档内容')
      return
    }

    setLoading(true)
    setError('')
    setResult(null)
    setBatchResults([])
    setMarkdown('')
    setObsidian('')
    setMindmap('')
    setMindmapSvg(null)
    setMindmapError(null)
    setExportTab('markdown')
    setCopied(null)
    setPlan(null)
    setExecution([])
    setReflection(null)
    setAgentMeta(null)
    setToolCalls([])
    setIterations([])
    setTotalIterations(0)
    setUiMode('simple')
    setMarkdownPreviewOpen(false)
    setPipelineExpanded(false)

    // 启动可视化进度 — Stage 1 立即触发（Document Loaded）
    // 后续 Stage 2-7 由 SSE 实时推送（/api/research/multi-agent-stream）
    setProgressStage(1)
    setProgressStartedAt(Date.now())
    // 标记是否已完成（避免重复 set）
    let finalized = false
    const finalizeProgress = () => {
      if (finalized) return
      finalized = true
      setProgressStage(7) // 全部完成
      window.setTimeout(() => setProgressStage(0), 800)
    }

    try {
      if (mode === 'pdf') {
        // PDF 走 upload-pdf（先解析 PDF，再调 LLM）
        const formData = new FormData()
        formData.append('file', pdfFile as File)
        formData.append('language', 'zh')
        formData.append('detail_level', 'standard')
        formData.append('export_format', 'markdown')

        const pdfResponse = await fetch('/api/research/upload-pdf', {
          method: 'POST',
          body: formData,
        })
        const pdfData = await pdfResponse.json()
        if (!pdfData.success) {
          setError(pdfData.error || 'PDF 解析失败')
          setProgressStage(0)
          return
        }
        setResult(pdfData.knowledge_card)
        setMarkdown(pdfData.markdown || '')
        setObsidian(pdfData.obsidian || '')
        setMindmap(pdfData.mindmap || '')
        finalizeProgress()
        setLoading(false)
        return
      }

      // batch 模式不支持 SSE（每条 URL 各自走 multi-agent，进度难以聚合）
      if (mode === 'batch') {
        const urls = input.split('\n').map(u => u.trim()).filter(u => u.length > 0)
        const response = await fetch('/api/research/batch', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ urls, concurrency: 3 }),
        })
        const data = await response.json()
        if (!data.success) {
          setError(data.error || '生成失败')
          setProgressStage(0)
          return
        }
        setBatchResults(data.results || [])
        finalizeProgress()
        return
      }

      // text / url 模式：用 SSE 订阅真实进度
      let actualContent = input
      let actualSource: string = '用户输入'
      let actualTitle: string | undefined = undefined

      if (mode === 'url') {
        // URL 模式：先抓取 URL 内容，再走 SSE
        const fetchResponse = await fetch('/api/research/fetch-url', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ url: input }),
        })
        const fetchData = await fetchResponse.json()
        if (!fetchData.success) {
          setError(fetchData.error || 'URL 抓取失败')
          setProgressStage(0)
          return
        }
        if (!fetchData.content || fetchData.content.length < 50) {
          setError(`URL 抓取到的内容过短（${fetchData.content?.length || 0} 字符）。可能是 JS 渲染的页面，请改用文本模式粘贴内容。`)
          setProgressStage(0)
          return
        }
        // parser.ts 的 fetchFromUrl 已将内容截断到 30000 字符，此处无需再截断
        actualContent = fetchData.content
        actualSource = input
        actualTitle = fetchData.title
      }

      // 用 fetch + ReadableStream 接收 SSE（EventSource 不支持 POST，所以手动解析）
      const sseResponse = await fetch('/api/research/multi-agent-stream', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'Accept': 'text/event-stream' },
        body: JSON.stringify({ content: actualContent, source: actualSource, title: actualTitle }),
      }).catch((fetchErr: Error) => {
        // 网络层错误（如 ERR_ABORTED, ERR_CONNECTION_REFUSED）— 抛出友好消息给 catch 块
        const msg = String(fetchErr?.message || fetchErr)
        if (msg.includes('Failed to fetch') || msg.includes('NetworkError') || msg.includes('ABORTED')) {
          throw new Error('网络请求被中断（可能是页面刷新或代码热更新）。请稍等 1-2 秒后重试。')
        }
        throw fetchErr
      })

      if (!sseResponse.ok || !sseResponse.body) {
        const errText = await sseResponse.text()
        setError(`SSE 连接失败: ${sseResponse.status} ${errText}`)
        setProgressStage(0)
        return
      }

      // 手动解析 SSE 流
      const reader = sseResponse.body.getReader()
      const decoder = new TextDecoder()
      let buffer = ''
      let finalData: any = null

      try {
        while (true) {
          const { done, value } = await reader.read()
          if (done) break

          buffer += decoder.decode(value, { stream: true })

          // SSE 消息以 \n\n 分隔
          let idx: number
          while ((idx = buffer.indexOf('\n\n')) !== -1) {
            const rawMsg = buffer.slice(0, idx)
            buffer = buffer.slice(idx + 2)

            // 解析 event: xxx \n data: yyy
            const lines = rawMsg.split('\n')
            let eventName = 'message'
            const dataLines: string[] = []
            for (const line of lines) {
              if (line.startsWith('event: ')) eventName = line.slice(7)
              else if (line.startsWith('data: ')) dataLines.push(line.slice(6))
            }
            if (dataLines.length === 0) continue

            // JSON.parse 失败时跳过这条消息（不中断整个流）
            let payload: any
            try {
              payload = JSON.parse(dataLines.join('\n'))
            } catch (err) {
              console.warn('SSE JSON parse failed, skipping:', err)
              continue
            }

            if (eventName === 'stage') {
              // 真实后端进度更新
              setProgressStage(payload.id)
              if (payload.id === 7) {
                // Done — 800ms 后隐藏面板
                window.setTimeout(() => setProgressStage(0), 800)
              }
            } else if (eventName === 'result') {
              finalData = payload
            } else if (eventName === 'error') {
              setError(payload.error || '生成失败')
              setProgressStage(0)
              return
            }
          }
        }
      } catch (streamErr) {
        // 流读取过程中被中断（如 HMR 重新编译、页面刷新）
        const msg = String(streamErr instanceof Error ? streamErr.message : streamErr)
        if (msg.includes('aborted') || msg.includes('ABORTED') || msg.includes('network') || msg.includes('Failed to fetch')) {
          throw new Error('生成过程中连接被中断。请稍等 1-2 秒后重试。')
        }
        throw streamErr
      } finally {
        try { reader.releaseLock() } catch {}
      }

      if (!finalData || !finalData.success || !finalData.knowledge_card) {
        setError(finalData?.error || '生成失败：返回数据不完整')
        setProgressStage(0)
        return
      }

      setResult(finalData.knowledge_card)
      setMarkdown(finalData.markdown || '')
      setObsidian(finalData.obsidian || '')
      setMindmap(finalData.mindmap || '')
      setPlan(finalData.plan || null)
      setExecution(finalData.execution || [])
      setReflection(finalData.reflection || null)
      setAgentMeta(finalData.metadata || null)
      setToolCalls(finalData.tool_calls || [])
      setIterations(finalData.iterations || [])
      setTotalIterations(finalData.total_iterations || 0)
      finalizeProgress()
    } catch (err) {
      setError(err instanceof Error ? err.message : '请求失败')
      setProgressStage(0)
    } finally {
      setLoading(false)
    }
  }

  const copyMarkdown = (format: 'md' | 'obsidian' | 'mindmap') => {
    const content = format === 'md' ? markdown : format === 'obsidian' ? obsidian : mindmap
    // 用 try/catch 处理 clipboard 权限拒绝/非 HTTPS 等场景
    const fallbackCopy = () => {
      try {
        const textarea = document.createElement('textarea')
        textarea.value = content
        textarea.style.position = 'fixed'
        textarea.style.opacity = '0'
        document.body.appendChild(textarea)
        textarea.select()
        document.execCommand('copy')
        document.body.removeChild(textarea)
        return true
      } catch (e) {
        return false
      }
    }
    const ok = (() => {
      try {
        if (navigator.clipboard && window.isSecureContext) {
          navigator.clipboard.writeText(content).catch(() => {
            // 异步拒绝时回退
            if (!fallbackCopy()) {
              setError('复制失败：请手动选择文本复制')
              setTimeout(() => setError(''), 3000)
            }
          })
          return true
        }
        return fallbackCopy()
      } catch {
        return fallbackCopy()
      }
    })()
    if (ok) {
      setCopied(format)
      setTimeout(() => setCopied(null), 2000)
    }
  }

  const downloadMarkdown = (format: 'md' | 'obsidian' | 'mindmap') => {
    const content = format === 'md' ? markdown : format === 'obsidian' ? obsidian : mindmap
    const ext = format === 'mindmap' ? 'mmd' : 'md'
    const prefix = format === 'md' ? '' : format === 'obsidian' ? 'obsidian-' : 'mindmap-'
    const title = result?.title || 'knowledge-card'
    const blob = new Blob([content], { type: format === 'mindmap' ? 'text/plain;charset=utf-8' : 'text/markdown;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${prefix}${title.replace(/[^\w\u4e00-\u9fa5]+/g, '_')}.${ext}`
    a.click()
    URL.revokeObjectURL(url)
  }

  // Mermaid 渲染：mindmap 内容变化时重新渲染
  useEffect(() => {
    if (!mindmap || exportTab !== 'mindmap') {
      setMindmapSvg(null)
      setMindmapError(null)
      return
    }

    let cancelled = false

    const renderMermaid = async () => {
      try {
        setMindmapError(null)
        // 动态加载 mermaid（仅在需要时）
        const w = window as any
        if (!w.mermaid) {
          await new Promise<void>((resolve, reject) => {
            const script = document.createElement('script')
            script.src = 'https://cdn.jsdelivr.net/npm/mermaid@10.9.1/dist/mermaid.min.js'
            script.async = true
            script.onload = () => resolve()
            script.onerror = () => reject(new Error('Mermaid CDN 加载失败'))
            document.head.appendChild(script)
          })
        }
        const mermaid = w.mermaid
        mermaid.initialize({
          startOnLoad: false,
          theme: 'default',
          themeVariables: {
            primaryColor: '#ede9fe',
            primaryTextColor: '#4c1d95',
            primaryBorderColor: '#7c3aed',
            lineColor: '#a78bfa',
            fontSize: '14px',
          },
        })

        // 用唯一 id 避免重复渲染
        const id = `mindmap-${Date.now()}`
        const { svg } = await mermaid.render(id, mindmap)
        if (!cancelled) {
          setMindmapSvg(svg)
        }
      } catch (err) {
        if (!cancelled) {
          setMindmapSvg(null)
          setMindmapError(err instanceof Error ? err.message : 'Mermaid 渲染失败')
        }
      }
    }

    renderMermaid()

    return () => {
      cancelled = true
    }
  }, [mindmap, exportTab])

  const loadExample = () => {
    setMode('text')
    setInput(`Attention Is All You Need 是 Google 在 2017 年提出的 Transformer 架构论文。它完全摒弃了 RNN 和 CNN，只用 self-attention 机制处理序列。核心创新是 multi-head attention，让模型能同时关注序列中不同位置的信息。Transformer 在机器翻译任务上达到 SOTA，并成为后续 BERT、GPT 等大语言模型的基础架构。

该论文的主要贡献包括：
1. 提出了完全基于注意力机制的 Transformer 模型
2. 引入了 multi-head attention，让模型能同时关注不同表示子空间的信息
3. 使用 positional encoding 为模型提供位置信息
4. 在 WMT 2014 英语-德语翻译任务上达到 28.4 BLEU，比现有最好结果提升 2 BLEU以上

Transformer 的并行化能力使其训练速度远快于 RNN，为后续大规模预训练模型奠定了基础。`)
  }

  return (
    <div style={{ minHeight: '100vh', background: 'linear-gradient(135deg, #f6f8fc 0%, #e0e7ff 100%)', fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif' }}>
      {/* === Hero animations CSS === */}
      <style dangerouslySetInnerHTML={{ __html: `
        @keyframes fadeIn { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } }
        @keyframes fadeInUp { from { opacity: 0; transform: translateY(30px); } to { opacity: 1; transform: translateY(0); } }
        @keyframes float { 0%, 100% { transform: translateY(0); } 50% { transform: translateY(-12px); } }
        @keyframes pulse { 0%, 100% { transform: scale(1); opacity: 1; } 50% { transform: scale(1.05); opacity: 0.85; } }
        @keyframes flowDot {
          0% { left: 0%; opacity: 0; transform: scale(0.5); }
          10% { opacity: 1; transform: scale(1); }
          90% { opacity: 1; transform: scale(1); }
          100% { left: 100%; opacity: 0; transform: scale(0.5); }
        }
        @keyframes shimmer {
          0% { background-position: -200% center; }
          100% { background-position: 200% center; }
        }
        @keyframes orbit {
          0% { transform: rotate(0deg) translateX(36px) rotate(0deg); }
          100% { transform: rotate(360deg) translateX(36px) rotate(-360deg); }
        }
        @keyframes typing {
          from { width: 0; }
          to { width: 100%; }
        }
        @keyframes blink { 50% { opacity: 0; } }

        .hero-fade-up { animation: fadeInUp 0.7s ease-out both; }
        .hero-fade-delay-1 { animation: fadeInUp 0.7s ease-out 0.15s both; }
        .hero-fade-delay-2 { animation: fadeInUp 0.7s ease-out 0.3s both; }
        .hero-fade-delay-3 { animation: fadeInUp 0.7s ease-out 0.45s both; }
        .hero-fade-delay-4 { animation: fadeInUp 0.7s ease-out 0.6s both; }
        .hero-fade-delay-5 { animation: fadeInUp 0.7s ease-out 0.75s both; }

        .hero-float { animation: float 4s ease-in-out infinite; }
        .hero-pulse { animation: pulse 2.5s ease-in-out infinite; }

        .shimmer-text {
          background: linear-gradient(90deg, #6366f1 0%, #06b6d4 25%, #8b5cf6 50%, #06b6d4 75%, #6366f1 100%);
          background-size: 200% auto;
          background-clip: text;
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
          animation: shimmer 4s linear infinite;
        }

        .flow-track {
          position: relative;
          width: 100%;
          height: 4px;
          background: linear-gradient(90deg, #e0e7ff 0%, #c7d2fe 50%, #e0e7ff 100%);
          border-radius: 2px;
          overflow: visible;
          margin: 16px 0;
        }
        .flow-dot {
          position: absolute;
          top: 50%;
          width: 12px;
          height: 12px;
          background: linear-gradient(135deg, #6366f1, #06b6d4);
          border-radius: 50%;
          box-shadow: 0 0 16px rgba(99, 102, 241, 0.6);
          transform: translateY(-50%);
          animation: flowDot 3s ease-in-out infinite;
        }
        .flow-dot-2 { animation-delay: 1s; }
        .flow-dot-3 { animation-delay: 2s; }

        .agent-card {
          transition: all 0.35s cubic-bezier(0.4, 0, 0.2, 1);
          position: relative;
          overflow: hidden;
          cursor: default;
        }
        /* hover 时的彩色光晕（基于卡片自己的 borderLeft 颜色，用 currentColor 不可行 → 用伪元素叠色） */
        .agent-card::before {
          content: '';
          position: absolute;
          inset: 0;
          background: linear-gradient(135deg, rgba(99, 102, 241, 0.06) 0%, rgba(6, 182, 212, 0.06) 100%);
          opacity: 0;
          transition: opacity 0.3s ease;
          pointer-events: none;
        }
        .agent-card::after {
          /* 顶部扫光效果 */
          content: '';
          position: absolute;
          top: 0;
          left: -100%;
          width: 60%;
          height: 100%;
          background: linear-gradient(120deg, transparent 0%, rgba(255, 255, 255, 0.4) 50%, transparent 100%);
          transition: left 0.7s ease;
          pointer-events: none;
        }
        .agent-card:hover {
          transform: translateY(-6px) scale(1.03);
          box-shadow: 0 16px 32px rgba(99, 102, 241, 0.18), 0 0 0 1px rgba(99, 102, 241, 0.1);
          border-left-width: 5px;
        }
        .agent-card:hover::before { opacity: 1; }
        .agent-card:hover::after { left: 120%; }

        .typing-text {
          display: inline-block;
          overflow: hidden;
          white-space: nowrap;
          border-right: 2px solid #6366f1;
          animation: typing 3s steps(40, end) 1s both, blink 0.7s step-end infinite;
        }

        /* === 全局交互动效（不破坏业务逻辑，纯 CSS 增强） === */

        /* 通用按钮：hover 抬升 + 阴影 + 微缩 */
        button {
          transition: all 0.2s cubic-bezier(0.4, 0, 0.2, 1);
          position: relative;
          overflow: hidden;
        }
        button:hover:not(:disabled) {
          transform: translateY(-1px);
          box-shadow: 0 4px 12px rgba(99, 102, 241, 0.2);
        }
        button:active:not(:disabled) {
          transform: translateY(0) scale(0.97);
          box-shadow: 0 2px 6px rgba(99, 102, 241, 0.15);
        }
        /* 按钮点击波纹效果 */
        button::after {
          content: '';
          position: absolute;
          top: 50%;
          left: 50%;
          width: 0;
          height: 0;
          border-radius: 50%;
          background: rgba(255, 255, 255, 0.5);
          transform: translate(-50%, -50%);
          transition: width 0.6s ease, height 0.6s ease;
          pointer-events: none;
        }
        button:active::after {
          width: 200px;
          height: 200px;
          transition: 0s;
        }

        /* 输入框聚焦：边框流动 + 发光 */
        input:focus, textarea:focus {
          border-color: #6366f1 !important;
          box-shadow: 0 0 0 3px rgba(99, 102, 241, 0.1), 0 0 12px rgba(99, 102, 241, 0.15) !important;
        }

        /* 知识卡字段卡片：hover 丰富动效（抬升 + 光晕 + 扫光 + 色条变粗） */
        .hoverable-card {
          transition: all 0.35s cubic-bezier(0.4, 0, 0.2, 1);
          position: relative;
          overflow: hidden;
        }
        /* 彩色叠层（hover 时浮现） */
        .hoverable-card::before {
          content: '';
          position: absolute;
          inset: 0;
          background: linear-gradient(135deg, rgba(99, 102, 241, 0.05) 0%, rgba(6, 182, 212, 0.05) 100%);
          opacity: 0;
          transition: opacity 0.3s ease;
          pointer-events: none;
          z-index: 0;
        }
        /* 顶部扫光效果 */
        .hoverable-card::after {
          content: '';
          position: absolute;
          top: 0;
          left: -100%;
          width: 60%;
          height: 100%;
          background: linear-gradient(120deg, transparent 0%, rgba(255, 255, 255, 0.5) 50%, transparent 100%);
          transition: left 0.8s ease;
          pointer-events: none;
          z-index: 0;
        }
        .hoverable-card:hover {
          transform: translateY(-4px);
          box-shadow: 0 16px 32px rgba(99, 102, 241, 0.15), 0 0 0 1px rgba(99, 102, 241, 0.08);
          border-left-width: 6px !important;
        }
        .hoverable-card:hover::before { opacity: 1; }
        .hoverable-card:hover::after { left: 120%; }
        /* hover 时标题文字轻微右移 + 颜色加深 */
        .hoverable-card:hover > button > h3 {
          transform: translateX(4px);
          color: #4338ca !important;
          transition: all 0.3s ease;
        }
        .hoverable-card > button > h3 {
          transition: all 0.3s ease;
        }
        /* hover 时箭头颜色变深 */
        .hoverable-card:hover > button > span {
          color: #6366f1 !important;
          transition: color 0.3s ease;
        }
        .hoverable-card > button > span {
          transition: color 0.3s ease;
        }
        /* 让 children 在伪元素之上 */
        .hoverable-card > button,
        .hoverable-card > div {
          position: relative;
          z-index: 1;
        }

        /* 模式切换按钮：被选中时弹簧动画 */
        .mode-tab-active {
          animation: tab-pop 0.4s cubic-bezier(0.34, 1.56, 0.64, 1);
        }
        @keyframes tab-pop {
          0% { transform: scale(1); }
          50% { transform: scale(1.05); }
          100% { transform: scale(1); }
        }

        /* Hero chip：交错浮动 */
        .hero-chip {
          animation: chip-float 3s ease-in-out infinite;
        }
        .hero-chip:nth-child(2) { animation-delay: 0.2s; }
        .hero-chip:nth-child(3) { animation-delay: 0.4s; }
        .hero-chip:nth-child(4) { animation-delay: 0.6s; }
        .hero-chip:nth-child(5) { animation-delay: 0.8s; }
        .hero-chip:nth-child(6) { animation-delay: 1.0s; }
        @keyframes chip-float {
          0%, 100% { transform: translateY(0); }
          50% { transform: translateY(-4px); }
        }

        /* 进度阶段项：滑入 + 高亮闪动 */
        .stage-item {
          animation: stage-slide-in 0.5s cubic-bezier(0.4, 0, 0.2, 1) both;
        }
        @keyframes stage-slide-in {
          from { opacity: 0; transform: translateX(-12px); }
          to { opacity: 1; transform: translateX(0); }
        }

        /* Accordion 展开/收起过渡（用 max-height 模拟） */
        .accordion-body {
          overflow: hidden;
          transition: max-height 0.35s cubic-bezier(0.4, 0, 0.2, 1), opacity 0.25s ease;
        }

        /* 知识卡字段：渐入动画（按顺序） */
        .card-field-enter {
          animation: field-fade-up 0.5s ease-out both;
        }
        @keyframes field-fade-up {
          from { opacity: 0; transform: translateY(8px); }
          to { opacity: 1; transform: translateY(0); }
        }

        /* Logo 长按呼吸（覆盖原 hero-pulse，更柔和） */
        .logo-breath {
          animation: logo-breath 3.5s ease-in-out infinite;
        }
        @keyframes logo-breath {
          0%, 100% { transform: scale(1); box-shadow: 0 12px 32px rgba(99, 102, 241, 0.35); }
          50% { transform: scale(1.04); box-shadow: 0 16px 40px rgba(99, 102, 241, 0.5); }
        }

        /* Title 微弱发光脉冲（在彩色背景上仍清晰可见） */
        .title-glow {
          animation: title-glow 3s ease-in-out infinite;
        }
        @keyframes title-glow {
          0%, 100% { text-shadow: 0 0 8px rgba(255,255,255,0.3), 0 2px 4px rgba(0,0,0,0.2); }
          50% { text-shadow: 0 0 20px rgba(255,255,255,0.6), 0 4px 8px rgba(0,0,0,0.3); }
        }

        /* Copy 按钮成功反馈：脉冲绿 */
        .copy-success {
          animation: copy-pulse 0.6s ease-out;
        }
        @keyframes copy-pulse {
          0% { box-shadow: 0 0 0 0 rgba(16, 185, 129, 0.5); }
          100% { box-shadow: 0 0 0 12px rgba(16, 185, 129, 0); }
        }

        /* 错误提示震动 */
        .error-shake {
          animation: shake 0.5s cubic-bezier(0.36, 0.07, 0.19, 0.97) both;
        }
        @keyframes shake {
          10%, 90% { transform: translateX(-1px); }
          20%, 80% { transform: translateX(2px); }
          30%, 50%, 70% { transform: translateX(-3px); }
          40%, 60% { transform: translateX(3px); }
        }

        /* Cap matrix card：hover 时显示渐变光晕 */
        .cap-card {
          position: relative;
          transition: all 0.3s ease;
        }
        .cap-card::before {
          content: '';
          position: absolute;
          inset: 0;
          border-radius: inherit;
          background: linear-gradient(135deg, rgba(99, 102, 241, 0.08) 0%, rgba(6, 182, 212, 0.08) 100%);
          opacity: 0;
          transition: opacity 0.3s ease;
          pointer-events: none;
        }
        .cap-card:hover::before { opacity: 1; }
        .cap-card:hover {
          transform: translateY(-4px);
          box-shadow: 0 16px 32px rgba(99, 102, 241, 0.15);
        }

        /* Pipeline 单行 summary chip：hover 时变亮 */
        .pipeline-chip {
          transition: all 0.2s ease;
        }
        .pipeline-chip:hover {
          transform: scale(1.08);
          filter: brightness(1.15);
        }

        /* Knowledge Graph branch：hover 时颜色加深 */
        .kg-branch-hover {
          transition: all 0.2s ease;
        }
        .kg-branch-hover:hover {
          transform: translateX(3px);
          filter: brightness(1.1);
          box-shadow: 0 4px 12px rgba(99, 102, 241, 0.2);
        }

        /* Footer / 输入区隔层：淡入 */
        .section-fade-in {
          animation: section-fade-in 0.6s ease-out both;
        }
        @keyframes section-fade-in {
          from { opacity: 0; transform: translateY(12px); }
          to { opacity: 1; transform: translateY(0); }
        }
      `}} />

      <main style={{ maxWidth: '1100px', margin: '0 auto', padding: '40px 20px' }}>
        {/* === HERO === */}
        <div style={{ textAlign: 'center', marginBottom: '48px', position: 'relative' }}>
          {/* Floating background blobs */}
          <div style={{
            position: 'absolute',
            top: '-20px',
            left: '50%',
            transform: 'translateX(-50%)',
            width: '320px',
            height: '320px',
            background: 'radial-gradient(circle, rgba(139, 92, 246, 0.15) 0%, transparent 70%)',
            borderRadius: '50%',
            zIndex: 0,
            pointerEvents: 'none',
          }} />

          {/* === Hero（精简版：只占第一屏的一部分，输入框优先可见） === */}
          {/* Logo */}
          <div className="hero-fade-up" style={{
            position: 'relative',
            display: 'inline-block',
            marginBottom: '12px',
            zIndex: 1,
          }}>
            <div className="logo-breath" style={{
              width: '56px',
              height: '56px',
              margin: '0 auto',
              background: 'linear-gradient(135deg, #6366f1 0%, #06b6d4 100%)',
              borderRadius: '16px',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              fontSize: '28px',
              boxShadow: '0 8px 24px rgba(99, 102, 241, 0.3)',
            }}>🔬</div>
          </div>

          {/* Title */}
          <h1 className="hero-fade-delay-1" style={{
            fontSize: '38px',
            fontWeight: 900,
            margin: 0,
            letterSpacing: '-0.02em',
            position: 'relative',
            zIndex: 1,
          }}>
            <span className="shimmer-text">ResearchKit OS</span>
          </h1>

          {/* One-liner slogan */}
          <p className="hero-fade-delay-2" style={{
            fontSize: '17px',
            fontWeight: 600,
            marginTop: '8px',
            color: '#0f172a',
            letterSpacing: '-0.005em',
            position: 'relative',
            zIndex: 1,
          }}>
            Read Less. <span style={{ color: '#6366f1' }}>Learn More.</span> <span style={{ color: '#06b6d4' }}>Build Faster.</span>
          </p>

          {/* Tiny tagline */}
          <p className="hero-fade-delay-3" style={{
            color: '#5a6478',
            fontSize: '13px',
            marginTop: '4px',
            fontWeight: 500,
            position: 'relative',
            zIndex: 1,
          }}>
            AI Research Agent · 论文/文档 → 结构化知识卡 + Knowledge Graph + 推荐阅读
          </p>
        </div>

        {/* === Input Card — 紧接 Hero，第一屏即可见 === */}
        <div className="section-fade-in hero-fade-delay-4" style={{ background: 'white', borderRadius: '20px', padding: '28px', boxShadow: '0 4px 20px rgba(99, 102, 241, 0.08)', marginTop: '24px', marginBottom: '24px' }}>
          {/* Mode tabs */}
          <div style={{ display: 'flex', gap: '8px', marginBottom: '20px', flexWrap: 'wrap' }}>
            <button key="text" onClick={() => { setMode('text'); setError('') }} style={tabStyle(mode === 'text')} className={mode === 'text' ? 'mode-tab-active' : ''}>📝 文本</button>
            <button key="url" onClick={() => { setMode('url'); setError('') }} style={tabStyle(mode === 'url')} className={mode === 'url' ? 'mode-tab-active' : ''}>🔗 URL</button>
            <button key="pdf" onClick={() => { setMode('pdf'); setError('') }} style={tabStyle(mode === 'pdf')} className={mode === 'pdf' ? 'mode-tab-active' : ''}>📄 PDF</button>
            <button key="batch" onClick={() => { setMode('batch'); setError('') }} style={tabStyle(mode === 'batch')} className={mode === 'batch' ? 'mode-tab-active' : ''}>⚡ 批量</button>
          </div>

          {/* Input field */}
          {mode === 'text' && (
            <textarea
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="粘贴论文摘要、技术文档或任意研究内容..."
              style={inputStyle}
              onFocus={(e) => (e.target.style.borderColor = '#6366f1')}
              onBlur={(e) => (e.target.style.borderColor = '#e2e8f2')}
            />
          )}

          {mode === 'url' && (
            <input
              type="url"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="https://arxiv.org/abs/2301.00001 或任意网页链接"
              style={{ ...inputStyle, minHeight: 'auto' }}
              onFocus={(e) => (e.target.style.borderColor = '#6366f1')}
              onBlur={(e) => (e.target.style.borderColor = '#e2e8f2')}
            />
          )}

          {mode === 'batch' && (
            <>
              <textarea
                value={input}
                onChange={(e) => setInput(e.target.value)}
                placeholder={'每行一个 URL，最多 10 个：\nhttps://arxiv.org/abs/1706.03762\nhttps://arxiv.org/abs/1810.04805\nhttps://arxiv.org/abs/2005.14165'}
                style={{ ...inputStyle, fontFamily: 'monospace', fontSize: '13px' }}
                onFocus={(e) => (e.target.style.borderColor = '#6366f1')}
                onBlur={(e) => (e.target.style.borderColor = '#e2e8f2')}
              />
              <div style={{ marginTop: '8px', fontSize: '13px', color: '#94a3b8' }}>
                ⚡ 3 并发处理 · 默认 brief 模式（节省 token）· 失败的 URL 不会中断其他
              </div>
            </>
          )}

          {mode === 'pdf' && (
            <div
              onDragOver={(e) => { e.preventDefault(); setDragging(true) }}
              onDragLeave={() => setDragging(false)}
              onDrop={(e) => {
                e.preventDefault()
                setDragging(false)
                const file = e.dataTransfer.files[0]
                if (!file) return
                if (!(file.name.toLowerCase().endsWith('.pdf') || file.type === 'application/pdf')) {
                  setError('只支持 PDF 文件')
                  return
                }
                // 客户端预校验大小，避免大文件上传后才报错（服务端 10MB 上限）
                if (file.size > 10 * 1024 * 1024) {
                  setError(`PDF 文件过大（${(file.size / 1024 / 1024).toFixed(1)} MB），最大支持 10 MB`)
                  return
                }
                setPdfFile(file)
                setError('')
              }}
              onClick={() => fileInputRef.current?.click()}
              style={{
                width: '100%',
                minHeight: '180px',
                border: `2px dashed ${dragging ? '#6366f1' : pdfFile ? '#10b981' : '#e2e8f2'}`,
                borderRadius: '12px',
                padding: '24px',
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                justifyContent: 'center',
                cursor: 'pointer',
                background: dragging ? '#f0f4ff' : pdfFile ? '#f0fdf4' : '#fafbfc',
                transition: 'all 0.2s',
                boxSizing: 'border-box',  // 避免 padding+border 让 width:100% 溢出容器
              }}
            >
              <input
                ref={fileInputRef}
                type="file"
                accept=".pdf,application/pdf"
                style={{ display: 'none' }}
                onChange={(e) => {
                  const file = e.target.files?.[0]
                  if (!file) return
                  if (file.size > 10 * 1024 * 1024) {
                    setError(`PDF 文件过大（${(file.size / 1024 / 1024).toFixed(1)} MB），最大支持 10 MB`)
                    return
                  }
                  setPdfFile(file)
                  setError('')
                }}
              />
              {pdfFile ? (
                <>
                  <div style={{ fontSize: '32px', marginBottom: '8px' }}>✓</div>
                  <div style={{ fontWeight: 600, color: '#10b981', marginBottom: '4px' }}>{pdfFile.name}</div>
                  <div style={{ fontSize: '13px', color: '#5a6478' }}>{(pdfFile.size / 1024).toFixed(1)} KB · 点击重新选择</div>
                </>
              ) : (
                <>
                  <div style={{ fontSize: '32px', marginBottom: '8px' }}>📄</div>
                  <div style={{ fontWeight: 600, color: '#5a6478', marginBottom: '4px' }}>点击上传或拖拽 PDF 到这里</div>
                  <div style={{ fontSize: '13px', color: '#94a3b8' }}>最大 10MB · 支持文字版 PDF</div>
                </>
              )}
            </div>
          )}

          {/* Actions */}
          <div style={{ display: 'flex', gap: '12px', marginTop: '20px', alignItems: 'center' }}>
            <button
              onClick={handleSubmit}
              disabled={loading}
              style={{
                flex: 1, padding: '14px 24px',
                background: loading ? '#cbd5e1' : 'linear-gradient(135deg, #6366f1 0%, #06b6d4 100%)',
                color: 'white', border: 'none', borderRadius: '12px',
                fontSize: '16px', fontWeight: 700, cursor: loading ? 'not-allowed' : 'pointer',
                transition: 'transform 0.2s', transform: loading ? 'none' : 'scale(1)',
              }}
            >
              {loading ? '⏳ 生成中...' : '✨ 生成知识卡'}
            </button>
            <button
              onClick={loadExample}
              style={{
                padding: '14px 20px', background: '#f1f5f9', color: '#5a6478',
                border: 'none', borderRadius: '12px', cursor: 'pointer',
                fontSize: '14px', fontWeight: 600,
              }}
            >📋 载入示例</button>
          </div>

          {/* 可视化生成进度面板 */}
          {progressStage > 0 && progressStage < 8 && (
            <div style={{
              marginTop: '20px',
              padding: '24px',
              background: 'linear-gradient(135deg, #f8fafc 0%, #eef2ff 100%)',
              borderRadius: '16px',
              border: '1px solid #e0e7ff',
            }}>
              {/* Header */}
              <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '20px' }}>
                <div style={{
                  width: '32px', height: '32px',
                  background: 'linear-gradient(135deg, #6366f1, #06b6d4)',
                  borderRadius: '8px',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  fontSize: '16px',
                  boxShadow: '0 4px 12px rgba(99, 102, 241, 0.3)',
                  animation: 'spin 2s linear infinite',
                }}>⚙️</div>
                <div>
                  <div style={{ fontSize: '14px', fontWeight: 700, color: '#0f172a' }}>
                    {progressStage === 7 ? '✓ 完成' : 'Agent Pipeline 执行中'}
                  </div>
                  <div style={{ fontSize: '11px', color: '#94a3b8' }}>
                    {progressStage < 7
                      ? `Stage ${progressStage} / 6 · 已耗时 ${Math.floor((Date.now() - progressStartedAt) / 1000)}s`
                      : `总耗时 ${Math.floor((Date.now() - progressStartedAt) / 1000)}s`
                    }
                  </div>
                </div>
                {/* 整体进度条 */}
                <div style={{ marginLeft: 'auto', width: '120px', height: '6px', background: '#e0e7ff', borderRadius: '3px', overflow: 'hidden' }}>
                  <div style={{
                    width: `${(progressStage / 6) * 100}%`,
                    height: '100%',
                    background: 'linear-gradient(90deg, #6366f1, #06b6d4)',
                    transition: 'width 0.5s ease',
                  }} />
                </div>
              </div>

              {/* Stage list */}
              <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                {STAGES.map((stage) => {
                  const stageState = progressStage > stage.id
                    ? 'done'
                    : progressStage === stage.id
                      ? 'active'
                      : 'pending'
                  return (
                    <div key={stage.id} className="stage-item" style={{
                      display: 'flex',
                      alignItems: 'center',
                      gap: '12px',
                      padding: '12px 14px',
                      borderRadius: '10px',
                      background: stageState === 'done' ? '#f0fdf4'
                        : stageState === 'active' ? 'white'
                        : 'transparent',
                      border: stageState === 'done' ? '1px solid #bbf7d0'
                        : stageState === 'active' ? '1px solid #c7d2fe'
                        : '1px solid transparent',
                      transition: 'all 0.4s ease',
                      transform: stageState === 'active' ? 'translateX(4px)' : 'translateX(0)',
                      animationDelay: `${stage.id * 0.08}s`,
                    }}>
                      {/* Status icon */}
                      <div style={{
                        width: '28px', height: '28px',
                        borderRadius: '50%',
                        display: 'flex', alignItems: 'center', justifyContent: 'center',
                        fontSize: '13px', fontWeight: 700,
                        flexShrink: 0,
                        background: stageState === 'done' ? '#10b981'
                          : stageState === 'active' ? '#6366f1'
                          : '#e2e8f0',
                        color: 'white',
                        transition: 'all 0.3s ease',
                        boxShadow: stageState === 'active' ? '0 0 0 4px rgba(99, 102, 241, 0.2)' : 'none',
                      }}>
                        {stageState === 'done' ? '✓'
                          : stageState === 'active' ? ''
                          : stage.icon}
                        {stageState === 'active' && (
                          <span style={{
                            display: 'inline-block',
                            width: '12px', height: '12px',
                            border: '2px solid white',
                            borderTopColor: 'transparent',
                            borderRadius: '50%',
                            animation: 'spin 0.8s linear infinite',
                          }} />
                        )}
                      </div>

                      {/* Label + desc */}
                      <div style={{ flex: 1, minWidth: 0 }}>
                        <div style={{
                          fontSize: '13px', fontWeight: 600,
                          color: stageState === 'done' ? '#065f46'
                            : stageState === 'active' ? '#0f172a'
                            : '#94a3b8',
                          transition: 'color 0.3s ease',
                        }}>
                          {stage.label}
                        </div>
                        <div style={{
                          fontSize: '11px', color: '#94a3b8',
                          marginTop: '2px',
                          opacity: stageState === 'pending' ? 0.6 : 1,
                        }}>
                          {stage.desc}
                        </div>
                      </div>

                      {/* Status badge */}
                      {stageState === 'done' && (
                        <span style={{ fontSize: '10px', color: '#10b981', fontWeight: 700 }}>DONE</span>
                      )}
                      {stageState === 'active' && (
                        <span style={{ fontSize: '10px', color: '#6366f1', fontWeight: 700, animation: 'pulse 1.5s ease-in-out infinite' }}>RUNNING</span>
                      )}
                    </div>
                  )
                })}
              </div>

              {/* Spin keyframe */}
              <style dangerouslySetInnerHTML={{ __html: `@keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }` }} />
            </div>
          )}

          {error && (
            <div key={error} className="error-shake" style={{ marginTop: '16px', padding: '14px 16px', background: '#fef2f2', border: '1px solid #fecaca', color: '#dc2626', borderRadius: '12px', fontSize: '14px' }}>
              ❌ {error}
            </div>
          )}
        </div>

        {/* === Capability Matrix — 移到输入框之后，不再占第一屏 === */}
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))',
          gap: '12px',
          marginBottom: '24px',
          marginTop: '8px',
        }}>
          {/* Agents header */}
          <div style={{ gridColumn: '1 / -1', display: 'flex', alignItems: 'center', gap: '8px', marginTop: '8px' }}>
            <span style={{ fontSize: '16px' }}>🧠</span>
            <h3 style={{ margin: 0, fontSize: '14px', fontWeight: 800, color: '#4f46e5', textTransform: 'uppercase', letterSpacing: '0.08em' }}>
              Agent Pipeline · Autonomous Workflow
            </h3>
          </div>

          {[
            { icon: '🧠', name: 'Planner', role: 'LLM 自主规划', color: '#6366f1' },
            { icon: '📖', name: 'Reader', role: '阅读理解', color: '#06b6d4' },
            { icon: '🔬', name: 'Analyzer', role: '深度分析', color: '#0891b2' },
            { icon: '🔤', name: 'Terminology', role: '术语分类', color: '#0e7490' },
            { icon: '🏗️', name: 'KB Builder', role: '汇总构建', color: '#7c3aed' },
            { icon: '📚', name: 'Recommend', role: 'arXiv 推荐', color: '#8b5cf6' },
            { icon: '📤', name: 'Export', role: '多格式导出', color: '#db2777' },
          ].map((a, i) => (
            <div key={i} className="agent-card" style={{
              background: 'white',
              borderRadius: '12px',
              padding: '14px',
              boxShadow: '0 2px 8px rgba(0,0,0,0.04)',
              borderLeft: `3px solid ${a.color}`,
            }}>
              <div style={{ fontSize: '18px', marginBottom: '4px' }}>{a.icon}</div>
              <div style={{ fontSize: '12px', fontWeight: 800, color: '#0f172a' }}>{a.name}</div>
              <div style={{ fontSize: '10px', color: '#5a6478', marginTop: '2px' }}>{a.role}</div>
            </div>
          ))}

          {/* Tools header */}
          <div style={{ gridColumn: '1 / -1', display: 'flex', alignItems: 'center', gap: '8px', marginTop: '8px' }}>
            <span style={{ fontSize: '16px' }}>🔧</span>
            <h3 style={{ margin: 0, fontSize: '14px', fontWeight: 800, color: '#0891b2', textTransform: 'uppercase', letterSpacing: '0.08em' }}>
              MCP Tools · Model Context Protocol
            </h3>
          </div>

          {[
            { icon: '💾', name: 'Memory', desc: '跨会话记忆读过论文', color: '#0891b2' },
            { icon: '📄', name: 'Filesystem', desc: '保存 .md / .json 文件', color: '#0e7490' },
            { icon: '🔍', name: 'Arxiv', desc: '搜索相关学术论文', color: '#06b6d4' },
            { icon: '🌐', name: 'Web Search', desc: 'DuckDuckGo 网络搜索', color: '#0891b2' },
          ].map((t, i) => (
            <div key={i} className="agent-card" style={{
              background: 'white',
              borderRadius: '12px',
              padding: '14px',
              boxShadow: '0 2px 8px rgba(0,0,0,0.04)',
              borderLeft: `3px solid ${t.color}`,
            }}>
              <div style={{ fontSize: '18px', marginBottom: '4px' }}>{t.icon}</div>
              <div style={{ fontSize: '12px', fontWeight: 800, color: '#0f172a' }}>{t.name}</div>
              <div style={{ fontSize: '10px', color: '#5a6478', marginTop: '2px' }}>{t.desc}</div>
            </div>
          ))}
        </div>

        {/* Result */}
        {result && (() => {
          const L = getLabels(result.language, result.locale)
          return (
          <div className="section-fade-in" key={`result-${result.title}-${result.year || ''}`}>
            <style dangerouslySetInnerHTML={{ __html: `@keyframes fadeIn { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } }` }} />

            {/* Simple / Advanced 切换 — 顶部固定 */}
            <div style={{ display: 'flex', justifyContent: 'center', marginBottom: '16px' }}>
              <div style={{ display: 'flex', background: 'white', borderRadius: '999px', padding: '4px', boxShadow: '0 4px 12px rgba(0,0,0,0.06)', border: '1px solid #e2e8f0' }}>
                <button
                  onClick={() => setUiMode('simple')}
                  style={{
                    padding: '8px 20px',
                    border: 'none',
                    borderRadius: '999px',
                    cursor: 'pointer',
                    background: uiMode === 'simple' ? 'linear-gradient(135deg, #6366f1 0%, #06b6d4 100%)' : 'transparent',
                    color: uiMode === 'simple' ? 'white' : '#5a6478',
                    fontWeight: 700,
                    fontSize: '13px',
                    transition: 'all 0.2s',
                  }}
                >📖 Simple</button>
                <button
                  onClick={() => setUiMode('advanced')}
                  style={{
                    padding: '8px 20px',
                    border: 'none',
                    borderRadius: '999px',
                    cursor: 'pointer',
                    background: uiMode === 'advanced' ? 'linear-gradient(135deg, #7c3aed 0%, #db2777 100%)' : 'transparent',
                    color: uiMode === 'advanced' ? 'white' : '#5a6478',
                    fontWeight: 700,
                    fontSize: '13px',
                    transition: 'all 0.2s',
                  }}
                >🔬 Advanced</button>
              </div>
            </div>

            {/* Agent Pipeline — 仅 Advanced 模式显示，压缩为单行 + 点击展开 */}
            {uiMode === 'advanced' && plan && (
              <div style={{ background: 'white', borderRadius: '16px', boxShadow: '0 4px 12px rgba(0,0,0,0.06)', marginBottom: '16px', border: '2px solid #e0e7ff', overflow: 'hidden' }}>
                <button
                  onClick={() => setPipelineExpanded(!pipelineExpanded)}
                  style={{
                    width: '100%',
                    padding: '16px 20px',
                    background: 'none',
                    border: 'none',
                    cursor: 'pointer',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'space-between',
                    gap: '12px',
                    boxSizing: 'border-box',
                  }}
                >
                  {/* 压缩单行：✓ Read ✓ Analyze ✓ Structure ✓ Reflect ✓ Export */}
                  <div style={{ display: 'flex', alignItems: 'center', gap: '6px', flexWrap: 'wrap' }}>
                    <span style={{ fontSize: '16px' }}>🧠</span>
                    <span style={{ fontSize: '11px', fontWeight: 800, color: '#4f46e5', textTransform: 'uppercase', letterSpacing: '0.08em', marginRight: '4px' }}>Pipeline</span>
                    {[
                      { label: 'Read', icon: '📖' },
                      { label: 'Analyze', icon: '🔬' },
                      { label: 'Structure', icon: '🏗️' },
                      { label: 'Reflect', icon: '🔁' },
                      { label: 'Export', icon: '📤' },
                    ].map((step, i) => {
                      const stepExec = execution.find((e: any) => e.agent?.toLowerCase().includes(step.label.toLowerCase().slice(0, 4)) || e.agent === step.label)
                      const success = stepExec ? stepExec.success : true
                      return (
                        <span key={i} style={{ display: 'inline-flex', alignItems: 'center', gap: '3px', padding: '3px 8px', background: success ? '#f0fdf4' : '#fef2f2', color: success ? '#065f46' : '#991b1b', borderRadius: '999px', fontSize: '11px', fontWeight: 700 }}>
                          <span style={{ fontSize: '10px' }}>{success ? '✓' : '✗'}</span>
                          {step.label}
                        </span>
                      )
                    })}
                    {iterations.length > 0 && (
                      <span style={{ padding: '3px 8px', background: '#fef3c7', color: '#92400e', borderRadius: '999px', fontSize: '11px', fontWeight: 700 }}>
                        🔁 {totalIterations} iter
                      </span>
                    )}
                    {toolCalls.length > 0 && (
                      <span style={{ padding: '3px 8px', background: '#fefce8', color: '#854d0e', borderRadius: '999px', fontSize: '11px', fontWeight: 700 }}>
                        🔧 {toolCalls.length} tools
                      </span>
                    )}
                    {agentMeta?.total_duration_ms && (
                      <span style={{ padding: '3px 8px', background: '#f1f5f9', color: '#5a6478', borderRadius: '999px', fontSize: '11px', fontWeight: 700 }}>
                        ⚡ {agentMeta.total_duration_ms}ms
                      </span>
                    )}
                  </div>
                  <span style={{ color: '#94a3b8', fontSize: '14px', fontWeight: 700, flexShrink: 0 }}>{pipelineExpanded ? '▾' : '▸'}</span>
                </button>

                {/* 展开内容：完整 Agent Pipeline */}
                {pipelineExpanded && (
                  <div style={{ padding: '0 20px 20px', borderTop: '1px solid #e2e8f0' }}>
                    {/* Planner rationale */}
                    <div style={{ background: '#f5f3ff', border: '1px solid #ddd6fe', borderRadius: '12px', padding: '14px 16px', marginTop: '14px' }}>
                      <div style={{ fontSize: '12px', fontWeight: 700, color: '#6d28d9', marginBottom: '6px', textTransform: 'uppercase', letterSpacing: '0.08em' }}>🪧 Planner Reasoning</div>
                      <div style={{ fontSize: '14px', color: '#1e1b4b', lineHeight: 1.6 }}>{plan.rationale}</div>
                      <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap', marginTop: '8px' }}>
                        {plan.input_type && <PipelineChip>类型: {plan.input_type}</PipelineChip>}
                        {plan.complexity && <PipelineChip>复杂度: {plan.complexity}</PipelineChip>}
                        {agentMeta?.planner_duration_ms && <PipelineChip>规划耗时: {agentMeta.planner_duration_ms}ms</PipelineChip>}
                        {agentMeta?.reflection_duration_ms && <PipelineChip>反思耗时: {agentMeta.reflection_duration_ms}ms</PipelineChip>}
                        {agentMeta?.total_duration_ms && <PipelineChip>总耗时: {agentMeta.total_duration_ms}ms</PipelineChip>}
                      </div>
                    </div>

                    {/* Reflection Loop */}
                    {iterations && iterations.length > 0 && (
                      <div style={{ marginTop: '14px' }}>
                        <div style={{ fontSize: '12px', fontWeight: 700, color: '#7c3aed', marginBottom: '8px', textTransform: 'uppercase', letterSpacing: '0.08em' }}>
                          🔁 Reflection Loop ({totalIterations} {totalIterations === 1 ? 'iteration' : 'iterations'})
                        </div>
                        <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                          {iterations.map((iter: any, i: number) => (
                            <div key={i} style={{ padding: '12px 14px', background: '#faf5ff', border: '1px solid #e9d5ff', borderRadius: '10px' }}>
                              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexWrap: 'wrap', marginBottom: '6px' }}>
                                <span style={{ fontSize: '11px', padding: '2px 8px', background: '#7c3aed', color: 'white', borderRadius: '4px', fontWeight: 700 }}>ITER {iter.iteration}</span>
                                <span style={{ fontSize: '14px' }}>{iter.reflection?.satisfied ? '✅' : '⚠️'}</span>
                                <strong style={{ fontSize: '12px', color: iter.reflection?.satisfied ? '#065f46' : '#92400e' }}>
                                  {iter.reflection?.satisfied ? 'Satisfied' : 'Needs Work'}
                                </strong>
                                <span style={{ fontSize: '11px', color: '#94a3b8' }}>reflect: {iter.reflection_duration_ms}ms</span>
                                {iter.replan_duration_ms && (
                                  <span style={{ fontSize: '11px', color: '#94a3b8' }}>+ replan: {iter.replan_duration_ms}ms</span>
                                )}
                                {iter.supplementary_duration_ms && (
                                  <span style={{ fontSize: '11px', color: '#94a3b8' }}>+ exec: {iter.supplementary_duration_ms}ms</span>
                                )}
                              </div>
                              {iter.reflection?.reasoning && (
                                <div style={{ fontSize: '12px', color: '#5a6478', marginBottom: '6px', fontStyle: 'italic' }}>
                                  💭 {iter.reflection.reasoning}
                                </div>
                              )}
                              {iter.reflection?.missing && iter.reflection.missing.length > 0 && (
                                <div style={{ fontSize: '11px', color: '#92400e', marginBottom: '6px' }}>
                                  Missing: {iter.reflection.missing.join(', ')}
                                </div>
                              )}
                              {iter.replan && (
                                <div style={{ marginTop: '6px', padding: '8px 10px', background: 'white', border: '1px dashed #c4b5fd', borderRadius: '6px' }}>
                                  <div style={{ fontSize: '11px', color: '#6d28d9', fontWeight: 600 }}>
                                    {iter.replan.should_continue ? '🔄 Replan: continuing with supplementary steps' : '🛑 Replan: stopping'}
                                  </div>
                                  <div style={{ fontSize: '11px', color: '#5a6478', marginTop: '2px' }}>{iter.replan.reasoning}</div>
                                  {iter.replan.supplementary_steps && iter.replan.supplementary_steps.length > 0 && (
                                    <div style={{ marginTop: '4px', fontSize: '11px' }}>
                                      <strong style={{ color: '#7c3aed' }}>补充步骤：</strong>
                                      {iter.replan.supplementary_steps.map((s: any, j: number) => (
                                        <span key={j} style={{ display: 'inline-block', margin: '2px 4px 2px 0', padding: '2px 6px', background: '#ede9fe', color: '#5b21b6', borderRadius: '4px', fontSize: '10px' }}>
                                          {s.agent}
                                        </span>
                                      ))}
                                    </div>
                                  )}
                                </div>
                              )}
                              {iter.supplementary_execution && iter.supplementary_execution.length > 0 && (
                                <div style={{ marginTop: '6px' }}>
                                  {iter.supplementary_execution.map((s: any, j: number) => (
                                    <div key={j} style={{ display: 'flex', alignItems: 'center', gap: '6px', padding: '4px 8px', background: s.success ? '#f0fdf4' : '#fef2f2', border: `1px solid ${s.success ? '#bbf7d0' : '#fecaca'}`, borderRadius: '4px', marginBottom: '3px', fontSize: '11px' }}>
                                      <span>{s.success ? '✓' : '✗'}</span>
                                      <strong>{s.step.agent}</strong>
                                      <span style={{ color: '#94a3b8' }}>{s.duration_ms}ms</span>
                                      <span style={{ color: '#5a6478', flex: 1, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{s.step.reason}</span>
                                    </div>
                                  ))}
                                </div>
                              )}
                            </div>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* Execution Trace */}
                    <div style={{ marginTop: '14px' }}>
                      <div style={{ fontSize: '12px', fontWeight: 700, color: '#475569', marginBottom: '8px', textTransform: 'uppercase', letterSpacing: '0.08em' }}>⚡ Execution Trace</div>
                      <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                        {execution.map((step: any, i: number) => (
                          <div key={i} style={{ display: 'flex', alignItems: 'center', gap: '10px', padding: '10px 14px', background: step.success ? '#f0fdf4' : '#fef2f2', border: `1px solid ${step.success ? '#bbf7d0' : '#fecaca'}`, borderRadius: '10px' }}>
                            <span style={{ fontSize: '16px' }}>{step.success ? '✓' : '✗'}</span>
                            <div style={{ flex: 1, minWidth: 0 }}>
                              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexWrap: 'wrap' }}>
                                <strong style={{ color: '#0f1729', fontSize: '14px' }}>{step.agent}</strong>
                                <span style={{ fontSize: '11px', padding: '2px 6px', background: '#e0e7ff', color: '#4f46e5', borderRadius: '4px' }}>Group {step.parallel_group}</span>
                                {!step.required && <span style={{ fontSize: '11px', padding: '2px 6px', background: '#fef3c7', color: '#92400e', borderRadius: '4px' }}>optional</span>}
                              </div>
                              {step.reason && <div style={{ fontSize: '12px', color: '#5a6478', marginTop: '2px' }}>{step.reason}</div>}
                            </div>
                            <span style={{ fontSize: '12px', color: '#94a3b8', fontWeight: 600 }}>{step.duration_ms}ms</span>
                          </div>
                        ))}
                      </div>
                    </div>

                    {/* Reflection result */}
                    {reflection && (
                      <div style={{ marginTop: '12px', background: reflection.satisfied ? '#ecfdf5' : '#fffbeb', border: `1px solid ${reflection.satisfied ? '#a7f3d0' : '#fde68a'}`, borderRadius: '12px', padding: '12px 16px' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                          <span style={{ fontSize: '16px' }}>{reflection.satisfied ? '🎯' : '⚠️'}</span>
                          <strong style={{ fontSize: '13px', color: reflection.satisfied ? '#065f46' : '#92400e' }}>Reflection: {reflection.satisfied ? 'Satisfied' : 'Needs More Work'}</strong>
                        </div>
                        {reflection.reasoning && <div style={{ fontSize: '12px', color: '#5a6478', marginTop: '4px' }}>{reflection.reasoning}</div>}
                        {reflection.missing && reflection.missing.length > 0 && (
                          <div style={{ fontSize: '12px', color: '#92400e', marginTop: '4px' }}>Missing: {reflection.missing.join(', ')}</div>
                        )}
                      </div>
                    )}

                    {/* MCP Tool Calls */}
                    {toolCalls && toolCalls.length > 0 && (
                      <div style={{ marginTop: '12px' }}>
                        <div style={{ fontSize: '12px', fontWeight: 700, color: '#475569', marginBottom: '8px', textTransform: 'uppercase', letterSpacing: '0.08em' }}>🔧 MCP Tool Calls (Autonomous)</div>
                        <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                          {toolCalls.map((tc: any, i: number) => (
                            <div key={i} style={{ padding: '12px 14px', background: tc.success ? '#fefce8' : '#fef2f2', border: `1px solid ${tc.success ? '#fde68a' : '#fecaca'}`, borderRadius: '10px' }}>
                              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexWrap: 'wrap' }}>
                                <span style={{ fontSize: '14px' }}>{tc.success ? '✓' : '✗'}</span>
                                <code style={{ padding: '2px 8px', background: '#1e293b', color: '#fbbf24', borderRadius: '4px', fontSize: '12px', fontWeight: 700 }}>{tc.tool}</code>
                                <span style={{ fontSize: '11px', padding: '2px 6px', background: '#e0e7ff', color: '#4f46e5', borderRadius: '4px' }}>by {tc.called_by}</span>
                                <span style={{ fontSize: '11px', color: '#94a3b8', fontWeight: 600 }}>{tc.duration_ms}ms</span>
                              </div>
                              {tc.input && Object.keys(tc.input).length > 0 && (
                                <div style={{ fontSize: '11px', color: '#5a6478', marginTop: '6px', fontFamily: 'ui-monospace, monospace', background: '#f8fafc', padding: '6px 8px', borderRadius: '4px', whiteSpace: 'pre-wrap', wordBreak: 'break-word' }}>
                                  {(() => {
                                    const preview: any = {}
                                    Object.entries(tc.input).slice(0, 4).forEach(([k, v]: [string, any]) => {
                                      preview[k] = typeof v === 'string' && v.length > 60 ? v.substring(0, 60) + '...' : v
                                    })
                                    return JSON.stringify(preview)
                                  })()}
                                </div>
                              )}
                              {tc.output && (
                                <div style={{ fontSize: '11px', color: tc.success ? '#065f46' : '#991b1b', marginTop: '4px' }}>
                                  → {typeof tc.output === 'object' ? JSON.stringify(tc.output).substring(0, 120) : String(tc.output).substring(0, 120)}
                                  {JSON.stringify(tc.output).length > 120 ? '...' : ''}
                                </div>
                              )}
                              {tc.error && (
                                <div style={{ fontSize: '11px', color: '#991b1b', marginTop: '4px' }}>→ Error: {tc.error}</div>
                              )}
                            </div>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* Meta footer */}
                    {agentMeta && (
                      <div style={{ marginTop: '12px', fontSize: '11px', color: '#94a3b8', display: 'flex', gap: '12px', flexWrap: 'wrap', justifyContent: 'flex-end' }}>
                        <span>🧠 Planner: {agentMeta.planner_duration_ms}ms</span>
                        <span>🔁 Reflect: {agentMeta.reflection_iterations} iter ({agentMeta.reflection_duration_ms}ms)</span>
                        {agentMeta.supplementary_steps_executed > 0 && (
                          <span>🔄 Supp: {agentMeta.supplementary_steps_executed} steps</span>
                        )}
                        {agentMeta.tool_calls_count > 0 && (
                          <span>🔧 Tools: {agentMeta.tool_calls_succeeded}/{agentMeta.tool_calls_count} ok ({agentMeta.tool_call_duration_ms}ms)</span>
                        )}
                        <span>⚡ Total: {agentMeta.total_duration_ms}ms</span>
                      </div>
                    )}
                  </div>
                )}
              </div>
            )}

            {/* Title card with metadata */}
            <div style={{ background: 'linear-gradient(135deg, #6366f1 0%, #06b6d4 100%)', borderRadius: '20px', padding: '28px', color: 'white', marginBottom: '16px', boxShadow: '0 8px 24px rgba(99, 102, 241, 0.25)' }}>
              <div style={{ fontSize: '14px', opacity: 0.8, marginBottom: '8px', textTransform: 'uppercase', letterSpacing: '0.1em' }}>{L.knowledgeCard}</div>
              <h2 className="title-glow" style={{ fontSize: '24px', fontWeight: 700, margin: '0 0 12px 0' }}>{result.title}</h2>
              {/* Meta chips */}
              <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap', marginTop: '8px' }}>
                {result.authors?.length > 0 && (
                  <Chip>✍️ {result.authors.slice(0, 3).join(', ')}{result.authors.length > 3 ? ' 等' : ''}</Chip>
                )}
                {result.field && <Chip>🏷️ {result.field}</Chip>}
                {result.year && <Chip>📅 {result.year}</Chip>}
                {result.difficulty && <Chip>📊 {result.difficulty}</Chip>}
                {result.reading_time_min && <Chip>⏱️ {result.reading_time_min} min</Chip>}
              </div>
            </div>

            {/* Summary */}
            {result.summary && (
              <Card title={L.summary} color="#0ea5e9" defaultOpen={true} index={1}>
                <p style={{ margin: 0, lineHeight: 1.8, fontSize: '15px', color: '#0f1729' }}>{result.summary}</p>
              </Card>
            )}

            {/* Research goals */}
            {result.research_goals?.length > 0 && (
              <Card title={L.researchGoals} color="#f97316" index={2}>
                <ol style={{ margin: 0, paddingLeft: '20px', lineHeight: 1.8 }}>
                  {result.research_goals.map((g: string, i: number) => (
                    <li key={i} style={{ marginBottom: '6px' }}>{g}</li>
                  ))}
                </ol>
              </Card>
            )}

            {/* Innovation */}
            {(result.innovation?.length > 0 || result.core_arguments?.length > 0) && (
              <Card title={L.innovation} color="#f59e0b" defaultOpen={true} index={3}>
                <ol style={{ margin: 0, paddingLeft: '20px', lineHeight: 1.8 }}>
                  {(result.innovation || result.core_arguments).map((arg: string, i: number) => (
                    <li key={i} style={{ marginBottom: '8px' }}>{arg}</li>
                  ))}
                </ol>
              </Card>
            )}

            {/* Methodology */}
            {result.methodology && (
              <Card title={L.methodology} color="#10b981" index={4}>
                <p style={{ margin: 0, lineHeight: 1.8 }}>{result.methodology}</p>
              </Card>
            )}

            {/* Experiments */}
            {result.experiments?.length > 0 && (
              <Card title={L.experiments} color="#8b5cf6" index={5}>
                <ol style={{ margin: 0, paddingLeft: '20px', lineHeight: 1.8 }}>
                  {result.experiments.map((e: string, i: number) => (
                    <li key={i} style={{ marginBottom: '6px' }}>{e}</li>
                  ))}
                </ol>
              </Card>
            )}

            {/* Results */}
            {result.results?.length > 0 && (
              <Card title={L.results} color="#06b6d4" index={6}>
                <ol style={{ margin: 0, paddingLeft: '20px', lineHeight: 1.8 }}>
                  {result.results.map((r: string, i: number) => (
                    <li key={i} style={{ marginBottom: '6px' }}>{r}</li>
                  ))}
                </ol>
              </Card>
            )}

            {/* Key terms */}
            {result.key_terms?.length > 0 && (
              <Card title={L.keyTerms} color="#06b6d4" index={7}>
                <div style={{ display: 'grid', gap: '12px' }}>
                  {result.key_terms.map((item: any, i: number) => (
                    <div key={i} style={{ padding: '12px', background: '#f8fafc', borderRadius: '8px', borderLeft: '3px solid #06b6d4' }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px' }}>
                        <span style={{ fontWeight: 700, color: '#0f1729' }}>{item.term}</span>
                        {item.category && (
                          <span style={{ fontSize: '11px', padding: '2px 8px', background: '#e0e7ff', color: '#4f46e5', borderRadius: '4px', textTransform: 'uppercase' }}>{item.category}</span>
                        )}
                      </div>
                      <div style={{ color: '#5a6478', fontSize: '14px' }}>{item.definition}</div>
                    </div>
                  ))}
                </div>
              </Card>
            )}

            {/* Applications */}
            {(result.applications?.length > 0 || result.actionable_takeaways?.length > 0) && (
              <Card title={L.applications} color="#6366f1" index={8}>
                <ul style={{ margin: 0, paddingLeft: '20px', lineHeight: 1.8 }}>
                  {(result.applications || result.actionable_takeaways).map((item: string, i: number) => (
                    <li key={i} style={{ marginBottom: '6px' }}>{item}</li>
                  ))}
                </ul>
              </Card>
            )}

            {/* Datasets */}
            {result.datasets?.length > 0 && (
              <Card title={L.datasets} color="#84cc16" index={9}>
                <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
                  {result.datasets.map((d: string, i: number) => (
                    <span key={i} style={{ padding: '6px 12px', background: '#f0fdf4', border: '1px solid #bbf7d0', color: '#4d7c0f', borderRadius: '999px', fontSize: '13px' }}>{d}</span>
                  ))}
                </div>
              </Card>
            )}

            {/* Limitations */}
            {result.limitations?.length > 0 && (
              <Card title={L.limitations} color="#ef4444" index={10}>
                <ul style={{ margin: 0, paddingLeft: '20px', lineHeight: 1.8 }}>
                  {result.limitations.map((l: string, i: number) => (
                    <li key={i} style={{ marginBottom: '6px' }}>{l}</li>
                  ))}
                </ul>
              </Card>
            )}

            {/* Future work */}
            {result.future_work?.length > 0 && (
              <Card title={L.futureWork} color="#a855f7" index={11}>
                <ul style={{ margin: 0, paddingLeft: '20px', lineHeight: 1.8 }}>
                  {result.future_work.map((f: string, i: number) => (
                    <li key={i} style={{ marginBottom: '6px' }}>{f}</li>
                  ))}
                </ul>
              </Card>
            )}

            {/* References / Recommended readings */}
            {result.references?.length > 0 && (
              <Card title={L.references} color="#8b5cf6" index={12}>
                <ul style={{ margin: 0, paddingLeft: '20px', fontSize: '14px', color: '#5a6478', lineHeight: 1.8 }}>
                  {result.references.map((ref: string, i: number) => (
                    <li key={i}>{ref}</li>
                  ))}
                </ul>
              </Card>
            )}

            {/* Tags */}
            {result.tags?.length > 0 && (
              <div style={{ background: 'white', borderRadius: '16px', padding: '16px 24px', boxShadow: '0 4px 12px rgba(0,0,0,0.06)', marginBottom: '16px' }}>
                <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
                  {result.tags.map((tag: string, i: number) => (
                    <span key={i} style={{ padding: '4px 10px', background: '#f1f5f9', color: '#5a6478', borderRadius: '6px', fontSize: '12px' }}>#{tag}</span>
                  ))}
                </div>
              </div>
            )}

            {/* Export toolbar — 折叠式：默认只显示 3 按钮，点 Preview 才展开 */}
            {(markdown || obsidian || mindmap) && (
              <Card title="📥 导出" color="#6366f1" defaultOpen={true} index={13}>
                {/* Format toggle — 3 tabs */}
                <div style={{ display: 'flex', gap: '8px', alignItems: 'center', marginBottom: '12px', flexWrap: 'wrap' }}>
                  <div style={{ display: 'flex', background: '#f1f5f9', borderRadius: '8px', padding: '2px' }}>
                    <button
                      onClick={() => { setExportTab('markdown'); setMarkdownPreviewOpen(false) }}
                      style={{
                        padding: '6px 12px', border: 'none', borderRadius: '6px', cursor: 'pointer',
                        background: exportTab === 'markdown' ? 'white' : 'transparent',
                        color: exportTab === 'markdown' ? '#6366f1' : '#5a6478',
                        fontWeight: 600, fontSize: '13px', boxShadow: exportTab === 'markdown' ? '0 1px 3px rgba(0,0,0,0.1)' : 'none',
                      }}
                    >Markdown</button>
                    <button
                      onClick={() => { setExportTab('obsidian'); setMarkdownPreviewOpen(false) }}
                      style={{
                        padding: '6px 12px', border: 'none', borderRadius: '6px', cursor: 'pointer',
                        background: exportTab === 'obsidian' ? 'white' : 'transparent',
                        color: exportTab === 'obsidian' ? '#8b5cf6' : '#5a6478',
                        fontWeight: 600, fontSize: '13px', boxShadow: exportTab === 'obsidian' ? '0 1px 3px rgba(0,0,0,0.1)' : 'none',
                      }}
                    >🔮 Obsidian</button>
                    <button
                      onClick={() => { setExportTab('mindmap'); setMarkdownPreviewOpen(false) }}
                      style={{
                        padding: '6px 12px', border: 'none', borderRadius: '6px', cursor: 'pointer',
                        background: exportTab === 'mindmap' ? 'white' : 'transparent',
                        color: exportTab === 'mindmap' ? '#0891b2' : '#5a6478',
                        fontWeight: 600, fontSize: '13px', boxShadow: exportTab === 'mindmap' ? '0 1px 3px rgba(0,0,0,0.1)' : 'none',
                      }}
                    >🧠 Knowledge Graph</button>
                  </div>
                </div>

                {/* Obsidian hint */}
                {exportTab === 'obsidian' && (
                  <div style={{ marginBottom: '12px', padding: '10px 12px', background: '#f5f3ff', border: '1px solid #ddd6fe', color: '#6d28d9', borderRadius: '8px', fontSize: '13px' }}>
                    🔮 Obsidian 双链格式：术语自动用 <code style={{ background: '#ede9fe', padding: '2px 6px', borderRadius: '4px' }}>[[term]]</code> 包裹，含 YAML frontmatter，导入 Obsidian 后可形成知识图谱。
                  </div>
                )}

                {/* Knowledge Graph hint */}
                {exportTab === 'mindmap' && (
                  <div style={{ marginBottom: '12px', padding: '10px 12px', background: '#ecfeff', border: '1px solid #a5f3fc', color: '#0e7490', borderRadius: '8px', fontSize: '13px' }}>
                    🧠 Knowledge Graph：可折叠知识图谱。默认只展示主分支，点击节点展开叶子。底部可查看 Mermaid 源码用于 Obsidian / mermaid.live。
                  </div>
                )}

                {/* Button group: Preview / Copy / Download */}
                <div style={{ display: 'flex', gap: '8px', marginBottom: exportTab === 'mindmap' ? '12px' : '0' }}>
                  {/* Markdown / Obsidian tab：显示「预览」按钮切换源码视图 */}
                  {/* Knowledge Graph tab：KG 本身就是可视化预览，不需要单独的预览按钮 */}
                  {exportTab !== 'mindmap' && (
                    <button
                      onClick={() => setMarkdownPreviewOpen(!markdownPreviewOpen)}
                      style={{
                        ...btnSecondary,
                        background: markdownPreviewOpen ? '#ede9fe' : '#f1f5f9',
                        color: markdownPreviewOpen ? '#5b21b6' : '#5a6478',
                      }}
                    >
                      {markdownPreviewOpen ? '▾ 隐藏预览' : '▸ 预览'}
                    </button>
                  )}
                  <button
                    onClick={() => copyMarkdown(exportTab === 'markdown' ? 'md' : exportTab === 'obsidian' ? 'obsidian' : 'mindmap')}
                    className={copied === (exportTab === 'markdown' ? 'md' : exportTab === 'obsidian' ? 'obsidian' : 'mindmap') ? 'copy-success' : ''}
                    style={btnSecondary}
                  >
                    {copied === (exportTab === 'markdown' ? 'md' : exportTab === 'obsidian' ? 'obsidian' : 'mindmap') ? '✓ 已复制' : '📋 复制'}
                  </button>
                  <button
                    onClick={() => downloadMarkdown(exportTab === 'markdown' ? 'md' : exportTab === 'obsidian' ? 'obsidian' : 'mindmap')}
                    style={btnPrimary}
                  >
                    ⬇️ 下载
                  </button>
                </div>

                {/* Markdown / Obsidian — code view, hidden by default */}
                {exportTab !== 'mindmap' && markdownPreviewOpen && (
                  <pre style={{ background: '#0f172a', color: '#e2e8f0', padding: '16px', borderRadius: '8px', fontSize: '12px', overflow: 'auto', maxHeight: '400px', margin: '12px 0 0', whiteSpace: 'pre-wrap', wordBreak: 'break-word' }}>
                    {exportTab === 'obsidian' ? obsidian : markdown}
                  </pre>
                )}

                {/* Knowledge Graph — 可折叠 + 生成动画（替代静态 Mermaid Mindmap） */}
                {exportTab === 'mindmap' && (
                  <div>
                    {/* 优先：KnowledgeGraph 自渲染组件 */}
                    {result && (
                      <KnowledgeGraph
                        rootTitle={result.title || 'Untitled'}
                        tree={buildKnowledgeGraph(result)}
                        buildDurationMs={1500}
                      />
                    )}

                    {/* Mermaid 源码 — 默认折叠，点按钮才展开 */}
                    <div style={{ marginTop: '12px', paddingTop: '12px', borderTop: '1px dashed #e2e8f0' }}>
                      <button
                        onClick={() => setShowMermaidSource(!showMermaidSource)}
                        style={{
                          padding: '6px 12px',
                          background: showMermaidSource ? '#0f172a' : '#f1f5f9',
                          color: showMermaidSource ? '#67e8f9' : '#5a6478',
                          border: 'none',
                          borderRadius: '6px',
                          cursor: 'pointer',
                          fontSize: '12px',
                          fontWeight: 600,
                        }}
                      >
                        {showMermaidSource ? '▾ 隐藏 Mermaid 源码' : '▸ 查看 Mermaid 源码（用于 Obsidian / mermaid.live）'}
                      </button>
                      {showMermaidSource && mindmap && (
                        <pre style={{ background: '#0f172a', color: '#67e8f9', padding: '12px', borderRadius: '8px', fontSize: '11px', overflow: 'auto', maxHeight: '240px', margin: '8px 0 0', whiteSpace: 'pre-wrap', wordBreak: 'break-word' }}>
                          {mindmap}
                        </pre>
                      )}
                      {/* 兼容老错误提示 */}
                      {mindmapError && showMermaidSource && (
                        <div style={{ marginTop: '8px', padding: '10px 12px', background: '#fef2f2', border: '1px solid #fecaca', color: '#991b1b', borderRadius: '8px', fontSize: '12px' }}>
                          ⚠️ Mermaid 源码渲染失败（不影响 Knowledge Graph）：{mindmapError}
                        </div>
                      )}
                    </div>
                  </div>
                )}
              </Card>
            )}
          </div>
          )
        })()}

        {/* Batch results — 独立于 result，批量模式不 set result，所以必须放外面 */}
        {batchResults.length > 0 && (
          <div className="section-fade-in" style={{ marginTop: '20px' }}>
            <div style={{ background: 'linear-gradient(135deg, #f59e0b 0%, #ef4444 100%)', borderRadius: '16px', padding: '20px', color: 'white', marginBottom: '16px' }}>
              <h3 style={{ margin: 0, fontSize: '18px', fontWeight: 700 }}>⚡ 批量处理结果</h3>
              <p style={{ margin: '4px 0 0 0', fontSize: '14px', opacity: 0.9 }}>
                共 {batchResults.length} 个 URL · 成功 {batchResults.filter(r => r.success).length} · 失败 {batchResults.filter(r => !r.success).length}
              </p>
            </div>
            {batchResults.map((r, i) => (
              <div key={i} style={{ background: 'white', borderRadius: '12px', padding: '16px', marginBottom: '12px', boxShadow: '0 2px 8px rgba(0,0,0,0.05)', borderLeft: `4px solid ${r.success ? '#10b981' : '#ef4444'}` }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'start', marginBottom: '8px' }}>
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div style={{ fontSize: '13px', color: '#94a3b8', marginBottom: '4px', wordBreak: 'break-all' }}>{r.url}</div>
                    {r.success ? (
                      <div style={{ fontWeight: 700, color: '#0f1729' }}>{r.knowledge_card?.title}</div>
                    ) : (
                      <div style={{ color: '#dc2626', fontSize: '14px' }}>❌ {r.error}</div>
                    )}
                  </div>
                  {r.success && (
                    <button
                      onClick={() => {
                        navigator.clipboard.writeText(r.markdown)
                        setCopied('md')
                        setTimeout(() => setCopied(null), 2000)
                      }}
                      className={copied === 'md' ? 'copy-success' : ''}
                      style={{ ...btnSecondary, fontSize: '12px', padding: '6px 10px' }}
                    >{copied === 'md' ? '✓' : '📋'}</button>
                  )}
                </div>
                {r.success && (r.knowledge_card?.innovation?.length > 0 || r.knowledge_card?.core_arguments?.length > 0) && (
                  <ul style={{ margin: '8px 0 0 0', paddingLeft: '20px', fontSize: '13px', color: '#5a6478', lineHeight: 1.6 }}>
                    {(r.knowledge_card.innovation || r.knowledge_card.core_arguments).slice(0, 3).map((arg: string, j: number) => (
                      <li key={j}>{arg}</li>
                    ))}
                  </ul>
                )}
              </div>
            ))}
          </div>
        )}

        {/* Footer */}
        <div style={{ textAlign: 'center', marginTop: '40px', padding: '20px', color: '#94a3b8', fontSize: '13px' }}>
          <strong style={{ color: '#5a6478' }}>ResearchKit OS v0.9.0</strong> — AI Research Operating System<br />
          <span style={{ fontSize: '12px' }}>Powered by DeepSeek · AI Research Pipeline · Agent Workflow + MCP Tools + Reflection Loop · 3 Export Formats (MD / Obsidian / Knowledge Graph) · Built for OKX.AI Genesis Hackathon</span>
        </div>
      </main>
    </div>
  )
}

function Card({ title, color, children, defaultOpen = false, index = 0 }: { title: string; color: string; children: React.ReactNode; defaultOpen?: boolean; index?: number }) {
  const [open, setOpen] = useState(defaultOpen)
  return (
    <div
      className="hoverable-card card-field-enter"
      style={{
        background: 'white',
        borderRadius: '16px',
        boxShadow: '0 4px 12px rgba(0,0,0,0.06)',
        marginBottom: '16px',
        borderLeft: `4px solid ${color}`,
        overflow: 'hidden',
        animationDelay: `${index * 0.08}s`,
      }}
    >
      <button
        onClick={() => setOpen(!open)}
        style={{
          width: '100%',
          padding: '16px 24px',
          background: 'none',
          border: 'none',
          cursor: 'pointer',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          gap: '12px',
          textAlign: 'left',
          boxSizing: 'border-box',
        }}
      >
        <h3 style={{ margin: 0, fontSize: '17px', fontWeight: 700, color: '#0f1729' }}>{title}</h3>
        <span style={{ color: '#94a3b8', fontSize: '14px', fontWeight: 700, flexShrink: 0, transition: 'transform 0.3s ease', display: 'inline-block', transform: open ? 'rotate(0deg)' : 'rotate(-90deg)' }}>▾</span>
      </button>
      {open && (
        <div className="accordion-body" style={{ padding: '0 24px 20px', maxHeight: '5000px', opacity: 1 }}>
          {children}
        </div>
      )}
    </div>
  )
}

function Chip({ children }: { children: React.ReactNode }) {
  return (
    <span style={{ display: 'inline-flex', alignItems: 'center', padding: '4px 10px', background: 'rgba(255,255,255,0.2)', backdropFilter: 'blur(4px)', borderRadius: '999px', fontSize: '12px', fontWeight: 500 }}>{children}</span>
  )
}

function PipelineChip({ children }: { children: React.ReactNode }) {
  return (
    <span className="pipeline-chip" style={{ display: 'inline-flex', alignItems: 'center', padding: '3px 10px', background: 'white', border: '1px solid #ddd6fe', color: '#6d28d9', borderRadius: '999px', fontSize: '11px', fontWeight: 600 }}>{children}</span>
  )
}

const btnPrimary: React.CSSProperties = {
  padding: '10px 16px',
  background: 'linear-gradient(135deg, #6366f1 0%, #06b6d4 100%)',
  color: 'white',
  border: 'none',
  borderRadius: '8px',
  cursor: 'pointer',
  fontSize: '14px',
  fontWeight: 600,
}

const btnSecondary: React.CSSProperties = {
  padding: '10px 16px',
  background: '#f1f5f9',
  color: '#5a6478',
  border: 'none',
  borderRadius: '8px',
  cursor: 'pointer',
  fontSize: '14px',
  fontWeight: 600,
}

function tabStyle(active: boolean): React.CSSProperties {
  return {
    flex: 1,
    padding: '10px 16px',
    borderRadius: '10px',
    border: 'none',
    cursor: 'pointer',
    background: active ? 'linear-gradient(135deg, #6366f1 0%, #06b6d4 100%)' : '#f1f5f9',
    color: active ? 'white' : '#5a6478',
    fontWeight: 600,
    fontSize: '14px',
  }
}

const inputStyle: React.CSSProperties = {
  width: '100%',
  minHeight: '180px',
  padding: '16px',
  border: '2px solid #e2e8f2',
  borderRadius: '12px',
  fontSize: '14px',
  fontFamily: 'inherit',
  resize: 'vertical',
  outline: 'none',
  transition: 'border-color 0.2s',
  boxSizing: 'border-box',  // 关键：避免 padding+border 让 width:100% 溢出容器
  display: 'block',          // 避免内联元素的基线对齐导致的下方空隙
  margin: 0,
}
