/**
 * UI 标签多语言映射
 *
 * v2.0 重构 — 从 app/page.tsx 抽出
 * 根据 locale 切换 UI 标签（中文论文用中文标签，英文论文用英文标签）
 */

export interface UiLabels {
  knowledgeCard: string
  authors: string
  field: string
  year: string
  difficulty: string
  readingTime: string
  min: string
  takeaway: string
  whyItMatters: string
  whatSurprised: string
  whoShouldRead: string
  summary: string
  researchGoals: string
  innovation: string
  methodology: string
  experiments: string
  results: string
  limitations: string
  futureWork: string
  applications: string
  datasets: string
  keyTerms: string
  recommendations: string
  references: string
  structure: string
  andOthers: string
  quality: string
  completeness: string
  confidence: string
  evidence: string
  tags: string
  generatedBy: string
}

/**
 * 按语言切换 UI 标签
 * - zh-CN → 中文标签
 * - 其他 locale → 英文标签（统一 fallback）
 * - 兼容旧的 language 字段（'zh' 仍走中文路径）
 */
export function getLabels(language?: string, locale?: string): UiLabels {
  const isZh = language === 'zh' || locale === 'zh-CN'
  return {
    knowledgeCard: isZh ? '📖 知识卡' : '📖 Knowledge Card',
    authors: isZh ? '作者' : 'Authors',
    field: isZh ? '领域' : 'Field',
    year: isZh ? '年份' : 'Year',
    difficulty: isZh ? '难度' : 'Difficulty',
    readingTime: isZh ? '阅读时长' : 'Reading time',
    min: isZh ? '分钟' : 'min',
    takeaway: isZh ? '🎯 核心结论' : '🎯 Takeaway',
    whyItMatters: isZh ? '💭 为什么重要' : '💭 Why It Matters',
    whatSurprised: isZh ? '✨ 最令人意外' : '✨ What Surprised Me',
    whoShouldRead: isZh ? '👥 谁应该读' : '👥 Who Should Read',
    summary: isZh ? '📌 一句话摘要' : '📌 Summary',
    researchGoals: isZh ? '🎯 研究目的' : '🎯 Research Goals',
    innovation: isZh ? '💡 创新点 / 主要贡献' : '💡 Innovation / Key Contributions',
    methodology: isZh ? '🔧 方法论' : '🔧 Methodology',
    experiments: isZh ? '🧪 实验设置' : '🧪 Experiments',
    results: isZh ? '📊 主要结果' : '📊 Results',
    limitations: isZh ? '⚠️ 局限性' : '⚠️ Limitations',
    futureWork: isZh ? '🔮 未来工作' : '🔮 Future Work',
    applications: isZh ? '🚀 应用场景' : '🚀 Applications',
    datasets: isZh ? '📁 数据集' : '📁 Datasets',
    keyTerms: isZh ? '🔤 关键术语' : '🔤 Key Terms',
    recommendations: isZh ? '📚 推荐阅读' : '📚 Recommended Reading',
    references: isZh ? '📚 参考文献 / 推荐阅读' : '📚 References',
    structure: isZh ? '📐 文章结构' : '📐 Structure',
    andOthers: isZh ? '等' : 'et al.',
    quality: isZh ? '质量评分' : 'Quality',
    completeness: isZh ? '完整度' : 'Completeness',
    confidence: isZh ? '置信度' : 'Confidence',
    evidence: isZh ? '证据强度' : 'Evidence',
    tags: isZh ? '标签' : 'Tags',
    generatedBy: isZh ? '由 ResearchKit OS 生成 — AI 研究操作系统' : 'Generated by ResearchKit OS — AI Research Operating System',
  }
}
